# Generated by Django 5.0.1 on 2024-01-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='xdadxas', max_length=255),
            preserve_default=False,
        ),
    ]
