# Generated by Django 5.0.1 on 2024-01-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_post_image_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
